/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CollectionsFrame.java
 *
 * Created on Sep 10, 2011, 9:46:48 PM
 */
package GUI;

import MetEvalmain.MetEvalApp;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import meteval.types.MetModel;
import meteval.types.MetModelCollection;

/**
 *
 * @author gieku
 */
public class CollectionsFrame extends javax.swing.JFrame {

    /** Creates new form CollectionsFrame */
    public CollectionsFrame(MetEvalApp app ){
        initComponents();
        this.repo   = app.getRepo();
        this.edited = new MetModelCollection();
        fillComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.app = app;
        this.setVisible(true);
    }
    public CollectionsFrame(MetEvalApp app,MetModelCollection toBeEdited){
        initComponents();
        this.repo   = app.getRepo();
        this.edited = toBeEdited;
        fillComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.app = app;
        this.setVisible(true);
    }
    private MetEvalApp app;
    private void fillComponents(){
        this.updateCollectionList();
        this.updateRepoList();
    }
    private MetModelCollection repo;
    private MetModelCollection edited;
    private void updateRepoList(){
        DefaultListModel repoListModel = new DefaultListModel();
        this.repoList.setModel(repoListModel);
        DefaultListModel colModel = (DefaultListModel) this.collectionList.getModel();
        if(repo != null)
        for(MetModel model:repo.getModels()){
            if(!colModel.contains(model))repoListModel.addElement(model);
        }
    }
    private void updateCollectionList(){
        DefaultListModel repoListModel = new DefaultListModel();
        this.collectionList.setModel(repoListModel);
        
        for(MetModel model:edited.getModels()){
            
            
            repoListModel.addElement(model);
        }
        updateRepoList();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        repoList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        collectionList = new javax.swing.JList();
        toCollectionButton = new javax.swing.JButton();
        fromCollectionButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        addModelToRepoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        repoList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        repoList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        repoList.setName("repoList"); // NOI18N
        jScrollPane1.setViewportView(repoList);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        collectionList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        collectionList.setName("collectionList"); // NOI18N
        jScrollPane2.setViewportView(collectionList);

        toCollectionButton.setText("->");
        toCollectionButton.setName("toCollectionButton"); // NOI18N
        toCollectionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toCollectionButtonMouseClicked(evt);
            }
        });

        fromCollectionButton.setText("<-");
        fromCollectionButton.setName("fromCollectionButton"); // NOI18N
        fromCollectionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fromCollectionButtonMouseClicked(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.setName("saveButton"); // NOI18N
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("collection name");
        jLabel1.setName("jLabel1"); // NOI18N

        nameField.setText("collectionName");
        nameField.setName("nameField"); // NOI18N

        addModelToRepoButton.setText("Import new model");
        addModelToRepoButton.setName("addModelToRepoButton"); // NOI18N
        addModelToRepoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addModelToRepoButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Add model ");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Remove model");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addModelToRepoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromCollectionButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(toCollectionButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(toCollectionButton)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fromCollectionButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(addModelToRepoButton)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(cancelButton))
                        .addGap(63, 63, 63)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addModelToRepoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addModelToRepoButtonMouseClicked
        JFileChooser chooser = new JFileChooser();
       chooser.setMultiSelectionEnabled(true);
        File[] selected ;
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            selected = chooser.getSelectedFiles();
            for(File file:selected){
                if(!isXML(file)){
                    JOptionPane.showMessageDialog(this, "File "+file.getAbsolutePath() + " does not belong to accepted format \n(must be .xml or .sbml)");
                    continue;
                }
                if(!isRedundant(file.getName())){
                    app.addNewModelsToRepo(file);
                }
                else JOptionPane.showMessageDialog(this, "Model "+ file.getName()+" already exists in the repository");
            }
                this.updateRepoList();
        }
    }//GEN-LAST:event_addModelToRepoButtonMouseClicked
private boolean isXML(File file){
    if(file.isFile()){
        String name = file.getName();
        if(name.endsWith(".xml") || name.endsWith(".sbml") )return true;
        else return false;
    }else return false;
}
    private boolean isRedundant(String name){
    name = stripExtension(name);
    MetModel model = app.getRepo().getModelByName(name);
    if(model != null)return true;
    else return false;
}
private String stripExtension(String name){
    int pos = name.lastIndexOf(".");
    if(pos == -1)return name;
    name.substring(0, pos);
    return name;
}
    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        saveCollectionName();
        app.removeCollection(edited);
        app.addCollection(edited);
        app.saveAll();
        this.dispose();
    }//GEN-LAST:event_saveButtonMouseClicked
private void saveCollectionName(){
    String name = this.nameField.getText();
    edited.setName(name);
}
    private void toCollectionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toCollectionButtonMouseClicked
        MetModel selected = (MetModel) this.repoList.getSelectedValue();
        if(selected != null){
            this.edited.addModel(selected);//TODO:check for redundancy
            this.updateCollectionList();
        }
    }//GEN-LAST:event_toCollectionButtonMouseClicked

    private void fromCollectionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fromCollectionButtonMouseClicked
        MetModel selected = (MetModel) this.collectionList.getSelectedValue();
        if(selected != null){
            edited.removeModel(selected);
            updateCollectionList();
        }
    }//GEN-LAST:event_fromCollectionButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addModelToRepoButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JList collectionList;
    private javax.swing.JButton fromCollectionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JList repoList;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton toCollectionButton;
    // End of variables declaration//GEN-END:variables
}
