/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResultFrame.java
 *
 * Created on Oct 26, 2011, 11:17:57 AM
 */
package GUI;

import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import meteval.SurreyWrapper.FbaResult;
import meteval.SurreyWrapper.Result;
import meteval.SurreyWrapper.TradeoffResult;

/**
 *
 * @author gieku
 */
public class ResultFrame extends javax.swing.JFrame {

    /** Creates new form ResultFrame */
    public ResultFrame(Result[] result) {
        initComponents();
        fillRawResults(result);
        populateComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("File");
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
private void fillRawResults(Result[] result){
    if(result[0] instanceof FbaResult)fillFbaResult(result);
    else if(result[0] instanceof TradeoffResult)fillTradeoffResult(result[0]);
}
    private HashMap<String,String> rawResults = new HashMap<String,String>();
    private void populateComponents() {
        DefaultTableModel tableModel = new DefaultTableModel();
        initTable(tableModel);
        for(String key:rawResults.keySet()){
            String val = rawResults.get(key);
            String[] vec = {key,val};
            tableModel.addRow(vec);
        }
    }
    private void initTable(DefaultTableModel tableModel){
        tableModel.addColumn("Tag");
        tableModel.addColumn("Result");
    }
    private void fillFbaResult(Result[] result) {
        for(Result partialResult:result){
            FbaResult fbaPres = (FbaResult) partialResult;
            String flux =""+ fbaPres.getResult();
            String modelName =  "" +partialResult.getAssociatedModel();
            rawResults.put(modelName, flux);
        }
    }

    private void fillTradeoffResult(Result result) {
        
    }
}
